# Generated by Django 6.0.7 on 2026-08-13 10:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('student', 'Sinh viên'), ('lecturer', 'Giảng viên'), ('staff', 'Nhân viên'), ('admin', 'Quản trị viên')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('master', 'Thạc sĩ'), ('doctor', 'Tiến sĩ'), ('assoc_prof', 'Phó Giáo sư'), ('prof', 'Giáo sư')], max_length=20, unique=True)),
                ('max_students_quota', models.PositiveIntegerField(help_text='Số đồ án/luận văn tối đa được hướng dẫn cùng lúc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('defense_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(help_text='Giáo vụ tạo hội đồng (create by the staff)', limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('chair', 'Chủ tịch hội đồng'), ('secretary', 'Thư ký'), ('member', 'Ủy viên'), ('reviewer', 'Ủy viên phản biện')], default='member', max_length=20)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='theses.committee')),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('head_of_faculty', models.OneToOneField(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='theses.faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='theses.faculty'),
        ),
        migrations.CreateModel(
            name='ListOfTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('technology', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'dễ'), ('medium', 'Trung bình'), ('difficult', 'Khó')], max_length=50)),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('major_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('training_duration', models.PositiveIntegerField(help_text='Số năm đào tạo, vd: 4')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='theses.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('status', models.CharField(choices=[('waiting_lecturer', 'Chờ phân giảng viên hướng dẫn'), ('assigned_lecturer', 'Đã phân giảng viên hướng dẫn')], default='waiting_lecturer', max_length=50)),
                ('wants_thesis_upgrade', models.BooleanField(default=False)),
                ('is_thesis', models.BooleanField(default=False)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('committee', models.ForeignKey(blank=True, help_text='Hội đồng phụ trách chấm/bảo vệ cho đồ án này (gán sau khi nộp báo cáo cuối kỳ).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='theses.committee')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_registrations', to=settings.AUTH_USER_MODEL)),
                ('upgraded_from', models.OneToOneField(blank=True, limit_choices_to={'is_thesis': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_to', to='theses.projectregistration')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationLecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('main', 'Chính thức'), ('option1', 'Tùy chọn 1'), ('option2', 'Tùy chọn 2'), ('reviewer', 'Phản biện')], default='main', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đồng ý'), ('rejected', 'Từ chối'), ('skipped', 'Không cần duyệt')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='Thời điểm giảng viên phản hồi (đồng ý/từ chối) nguyện vọng', null=True)),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='registration_assignments', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_assignments', to='theses.projectregistration')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateTimeField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='theses.projectregistration')),
                ('created_by', models.ForeignKey(help_text='Chỉ GVHD chính (MAIN) mới được tạo đợt', limit_choices_to={'role': 'main'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to='theses.registrationlecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('grade_type', models.CharField(choices=[('supervisor', 'Điểm GVHD'), ('reviewer', 'Điểm phản biện'), ('committee', 'Điểm hội đồng')], max_length=20)),
                ('is_final', models.BooleanField(default=True, help_text='True: điểm chính thức/tổng kết dùng để tính final_score. False: điểm thành phần do 1 thành viên hội đồng chấm, chờ tổng hợp.')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Trọng số điểm này trong tổng kết, vd 0.5 = 50%', max_digits=3)),
                ('comment', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by_committee_member', models.ForeignKey(blank=True, help_text='Dùng cho grade_type=committee. Hội đồng của thành viên này phải đang phụ trách registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to='theses.committeemember')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='theses.projectregistration')),
                ('graded_by_lecturer', models.ForeignKey(blank=True, help_text='Dùng cho grade_type=supervisor/reviewer. Phải thuộc đúng registration của Grade này.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to='theses.registrationlecturer')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('student_registration_start', models.DateTimeField(help_text='SV bắt đầu đăng ký')),
                ('student_registration_days', models.PositiveSmallIntegerField(default=14, help_text='Số ngày mở cho SV đăng ký, tính từ student_registration_start')),
                ('execution_duration_weeks', models.PositiveSmallIntegerField(default=10, help_text='Số tuần thực hiện đồ án, tính từ khi hết hạn đăng ký (student_registration_end). Dùng để tự động tính report_submission_start.')),
                ('report_submission_days', models.PositiveSmallIntegerField(default=7, help_text='Số ngày cho phép nộp báo cáo, tính từ report_submission_start')),
                ('status', models.CharField(choices=[('scheduled', 'Chờ mở đăng ký'), ('student_registration', 'Đang mở đăng ký'), ('in_progress', 'Đang thực hiện đồ án'), ('report_submission', 'Đang nhận báo cáo'), ('closed', 'Đã đóng')], default='scheduled', max_length=20)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_periods', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_periods', to='theses.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='projectregistration',
            name='registration_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_registrations', to='theses.registrationperiod'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('periodic', 'Báo cáo định kỳ'), ('final', 'Báo cáo cuối kỳ')], max_length=20)),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='periodic: lấy từ schedule.sequence_number. final: tự tăng theo số lần nộp lại.')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file_key', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Đã nộp'), ('reviewed', 'Đã xem/góp ý'), ('approved', 'Đã duyệt'), ('rejected', 'Yêu cầu nộp lại'), ('late', 'Nộp trễ')], default='submitted', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='theses.projectregistration')),
                ('reviewed_by_lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='theses.registrationlecturer')),
                ('schedule', models.ForeignKey(blank=True, help_text='Bắt buộc khi report_type=periodic, null khi report_type=final', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='theses.periodicreportschedule')),
            ],
            options={
                'ordering': ['registration', 'report_type', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='theses.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='projectregistration',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_registrations', to='theses.specialization'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lecturer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('academic_degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='theses.academicdegree')),
                ('specializations', models.ManyToManyField(blank=True, related_name='lecturers', to='theses.specialization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('training_type', models.CharField(choices=[('regular', 'Đại học chính quy'), ('distance', 'Đào tạo từ xa')], default='regular', max_length=50)),
                ('program_type', models.CharField(choices=[('standard', 'Đại trà'), ('high_quality', 'Chất lượng cao')], default='standard', max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('conduct_score', models.PositiveIntegerField(default=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='theses.major')),
            ],
        ),
        migrations.AddConstraint(
            model_name='committeemember',
            constraint=models.UniqueConstraint(fields=('committee', 'lecturer'), name='unique_lecturer_per_committee'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_faculty_name'),
        ),
        migrations.AddConstraint(
            model_name='committee',
            constraint=models.UniqueConstraint(fields=('faculty', 'name'), name='unique_committee_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'admin'), ('role', ''), ('faculty__isnull', False), _connector='OR'), name='faculty_required_unless_admin'),
        ),
        migrations.AddConstraint(
            model_name='listoftopics',
            constraint=models.UniqueConstraint(fields=('lecturer', 'title'), name='unique_topic_title_per_lecturer'),
        ),
        migrations.AddConstraint(
            model_name='major',
            constraint=models.UniqueConstraint(fields=('faculty', 'major_name'), name='unique_major_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='registrationlecturer',
            constraint=models.UniqueConstraint(fields=('registration', 'role'), name='unique_role_per_registration'),
        ),
        migrations.AddConstraint(
            model_name='registrationlecturer',
            constraint=models.UniqueConstraint(fields=('registration', 'lecturer'), name='unique_lecturer_per_registration'),
        ),
        migrations.AddConstraint(
            model_name='registrationlecturer',
            constraint=models.CheckConstraint(condition=models.Q(('approval_status__in', ['pending', 'skipped']), ('responded_at__isnull', False), _connector='OR'), name='responded_at_required_when_approved_or_rejected'),
        ),
        migrations.AddConstraint(
            model_name='periodicreportschedule',
            constraint=models.UniqueConstraint(fields=('registration', 'sequence_number'), name='unique_schedule_sequence_per_registration'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('registration', 'grade_type', 'graded_by_lecturer'), name='unique_grade_per_lecturer'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('registration', 'grade_type', 'graded_by_committee_member'), name='unique_grade_per_committee_member'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 10)), name='grade_score_between_0_and_10'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 1)), name='grade_weight_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('graded_by_lecturer__isnull', False), ('graded_by_committee_member__isnull', True)), models.Q(('graded_by_lecturer__isnull', True), ('graded_by_committee_member__isnull', False)), _connector='OR'), name='grade_graded_by_lecturer_xor_committee_member'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'student_registration', 'in_progress', 'report_submission'])), fields=('faculty',), name='unique_open_registration_period_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.CheckConstraint(condition=models.Q(('student_registration_days__gt', 0)), name='student_registration_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.CheckConstraint(condition=models.Q(('report_submission_days__gt', 0)), name='report_submission_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('registration', 'report_type', 'sequence_number'), name='unique_sequence_per_report_type_per_registration'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('report_type', 'periodic'), _negated=True), ('schedule__isnull', False), _connector='OR'), name='periodic_requires_schedule'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('report_type', 'final'), _negated=True), ('schedule__isnull', True), _connector='OR'), name='final_forbids_schedule'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by_lecturer__isnull', True), ('report_type', 'periodic'), _connector='OR'), name='reviewed_by_lecturer_only_for_periodic'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'late']), ('reviewed_at__isnull', False), _connector='OR'), name='reviewed_at_required_when_processed'),
        ),
        migrations.AddConstraint(
            model_name='specialization',
            constraint=models.UniqueConstraint(fields=('faculty', 'name'), name='unique_specialization_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='projectregistration',
            constraint=models.UniqueConstraint(fields=('student', 'registration_period'), name='unique_student_per_registration_period'),
        ),
        migrations.AddConstraint(
            model_name='projectregistration',
            constraint=models.CheckConstraint(condition=models.Q(('is_thesis', False), ('upgraded_from__isnull', False), _connector='OR'), name='thesis_requires_upgraded_from'),
        ),
        migrations.AddConstraint(
            model_name='projectregistration',
            constraint=models.CheckConstraint(condition=models.Q(('final_score__isnull', True), models.Q(('final_score__gte', 0), ('final_score__lte', 10)), _connector='OR'), name='final_score_between_0_and_10'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('gpa__gte', 0), ('gpa__lte', 4)), name='gpa_between_0_and_4'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('conduct_score__gte', 0), ('conduct_score__lte', 100)), name='conduct_score_between_0_and_100'),
        ),
    ]
