# Generated by Django 6.0.7 on 2026-08-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrationperiod',
            name='unique_open_registration_period_per_faculty',
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('status__in', ['scheduled', 'student_registration', 'in_progress', 'report_submission'])), fields=('faculty',), name='unique_open_registration_period_per_faculty'),
        ),
    ]
