# Generated by Django 6.0.7 on 2026-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='grade_graded_by_lecturer_xor_committee_member',
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('graded_by_lecturer__isnull', False), ('graded_by_committee_member__isnull', False), _negated=True), name='grade_graded_by_lecturer_xor_committee_member'),
        ),
    ]
