# Generated by Django 6.0.7 on 2026-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projectregistration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_faculty_name'),
        ),
        migrations.AddConstraint(
            model_name='listoftopics',
            constraint=models.UniqueConstraint(fields=('lecturer', 'title'), name='unique_topic_title_per_lecturer'),
        ),
        migrations.AddConstraint(
            model_name='major',
            constraint=models.UniqueConstraint(fields=('faculty', 'major_name'), name='unique_major_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='projectregistration',
            constraint=models.UniqueConstraint(fields=('student', 'registration_period'), name='unique_student_per_registration_period'),
        ),
        migrations.AddConstraint(
            model_name='registrationlecturer',
            constraint=models.CheckConstraint(condition=models.Q(('approval_status__in', ['pending', 'skipped']), ('responded_at__isnull', False), _connector='OR'), name='responded_at_required_when_approved_or_rejected'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'student_registration', 'in_progress', 'report_submission'])), fields=('faculty',), name='unique_open_registration_period_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.CheckConstraint(condition=models.Q(('student_registration_end__gt', models.F('student_registration_start'))), name='student_registration_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.CheckConstraint(condition=models.Q(('report_submission_end__gt', models.F('report_submission_start'))), name='report_submission_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='specialization',
            constraint=models.UniqueConstraint(fields=('faculty', 'name'), name='unique_specialization_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('gpa__gte', 0), ('gpa__lte', 4)), name='gpa_between_0_and_4'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('conduct_score__gte', 0), ('conduct_score__lte', 100)), name='conduct_score_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'admin'), ('faculty__isnull', False), _connector='OR'), name='faculty_required_unless_admin'),
        ),
    ]
