# Generated by Django 6.0.7 on 2026-09-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_remove_grade_grade_graded_by_lecturer_xor_committee_member_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrationperiod',
            name='unique_open_registration_period_per_faculty',
        ),
        migrations.AddField(
            model_name='registrationperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationperiod',
            name='parent_period',
            field=models.ForeignKey(blank=True, help_text='Bắt buộc khi period_type=thesis: đợt đồ án gốc mà đợt khóa luận này kế thừa.', limit_choices_to={'period_type': 'project'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_periods', to='theses.registrationperiod'),
        ),
        migrations.AddField(
            model_name='registrationperiod',
            name='period_type',
            field=models.CharField(choices=[('project', 'Đợt đồ án'), ('thesis', 'Đợt khóa luận')], default='project', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='execution_duration_weeks',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='report_submission_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='student_registration_days',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='student_registration_start',
            field=models.DateTimeField(help_text='Đồ án: SV bắt đầu đăng ký. Khóa luận: thời điểm bắt đầu thực hiện.'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('status__in', ['scheduled', 'student_registration', 'in_progress', 'report_submission'])), fields=('faculty', 'period_type'), name='unique_open_registration_period_per_faculty_type'),
        ),
        migrations.AddConstraint(
            model_name='registrationperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('period_type', 'thesis'), ('parent_period__isnull', False)), models.Q(('period_type', 'project'), ('parent_period__isnull', True)), _connector='OR'), name='parent_period_required_only_for_thesis'),
        ),
    ]
