# Generated by Django 6.0.7 on 2026-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('theses', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='faculty_required_unless_admin',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'admin'), ('role', ''), ('faculty__isnull', False), _connector='OR'), name='faculty_required_unless_admin'),
        ),
    ]
