# Generated by Django 6.0.7 on 2026-09-12 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_remove_registrationperiod_unique_open_registration_period_per_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAssignmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('defense_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviewer_sessions', to=settings.AUTH_USER_MODEL)),
                ('registration_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_sessions', to='theses.registrationperiod')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registrationlecturer',
            name='reviewer_session',
            field=models.ForeignKey(blank=True, help_text='Chỉ set khi role=reviewer, dùng để nhóm các đợt phản biện chung ngày/phòng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_assignments', to='theses.reviewerassignmentsession'),
        ),
        migrations.AddConstraint(
            model_name='registrationlecturer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('role', 'reviewer'), _negated=True), ('reviewer_session__isnull', False), _connector='OR'), models.Q(('role', 'reviewer'), ('reviewer_session__isnull', True), _connector='OR')), name='reviewer_session_required_only_for_reviewer_role'),
        ),
        migrations.AddConstraint(
            model_name='reviewerassignmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('defense_date__isnull', False)), name='reviewer_session_defense_date_required'),
        ),
    ]
