# Generated by Django 6.0.7 on 2026-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_registrationlecturer_priority_and_preference_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectregistration',
            name='status',
            field=models.CharField(choices=[('waiting_lecturer', 'Chờ phân giảng viên hướng dẫn'), ('assigned_lecturer', 'Đã phân giảng viên hướng dẫn'), ('waiting_staff_assignment', 'Các nguyện vọng bị từ chối, chờ giáo vụ phân công')], default='waiting_lecturer', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationlecturer',
            name='role',
            field=models.CharField(choices=[('main', 'Chính thức'), ('preference', 'Nguyện vọng'), ('reviewer', 'Phản biện')], default='main', max_length=20),
        ),
    ]
