# Generated by Django 6.0.7 on 2026-07-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_remove_user_faculty_required_unless_admin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrationlecturer',
            name='responded_at_required_when_approved_or_rejected',
        ),
        migrations.AlterField(
            model_name='registrationlecturer',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đồng ý'), ('rejected', 'Từ chối'), ('skipped', 'Không cần duyệt'), ('pending_transfer', 'Chờ chuyển')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='registrationlecturer',
            constraint=models.CheckConstraint(condition=models.Q(('approval_status__in', ['pending', 'skipped', 'pending_transfer']), ('responded_at__isnull', False), _connector='OR'), name='responded_at_required_when_approved_or_rejected'),
        ),
    ]
