# Generated by Django 6.0.7 on 2026-08-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_alter_projectregistration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'chưa công bố'), ('scheduled', 'Chờ mở đăng ký'), ('student_registration', 'Đang mở đăng ký'), ('in_progress', 'Đang thực hiện đồ án'), ('report_submission', 'Đang nhận báo cáo'), ('closed', 'Đã đóng')], default='draft', max_length=20),
        ),
    ]
