# Generated by Django 6.0.7 on 2026-09-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_reviewerassignmentsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='graded_by_committee_member',
            field=models.ForeignKey(blank=True, help_text='Dùng cho grade_type=committee. Hội đồng của thành viên này phải đang phụ trách registration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to='theses.committeemember'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graded_by_lecturer',
            field=models.ForeignKey(blank=True, help_text='Dùng cho grade_type=supervisor/reviewer. Phải thuộc đúng registration của Grade này.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to='theses.registrationlecturer'),
        ),
    ]
